// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.



// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"


// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function (s, t) {
  const tObject = {};

  for (let letter of t) {
    if (tObject[letter]) {
      tObject[letter] += 1;
    } else {
      tObject[letter] = 1;
    }
  };

  for (let letter of s) {
    if (tObject[letter] > 0) {
      tObject[letter] -= 1;
    }
  }

  for (let key in tObject) {
    if (tObject[key] > 0) {
      return key;
    }
  }
};

console.log(findTheDifference("", "y"))